# Generated by Django 4.2.10 on 2025-04-29 10:31

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Exercise description and instructions')),
                ('setup_code', models.TextField(help_text='SQL to initialize database (create tables, insert data)')),
                ('base_query', models.TextField(help_text="Query with placeholders (e.g., 'SELECT * FROM users WHERE name = :name')")),
                ('placeholders', models.JSONField(help_text="List of placeholder definitions. Format: [{'name': 'name', 'type': 'str|int|regex', 'regex_pattern': 'optional pattern'}]")),
                ('expected_flag', models.CharField(help_text='Flag that should appear in results when solved (case-insensitive check)', max_length=255)),
                ('show_tables', models.JSONField(blank=True, default=list, help_text='List of table names to display to user')),
                ('show_query', models.BooleanField(default=True, help_text='Whether to show the base query to user or just inputs')),
                ('show_errors', models.BooleanField(default=True, help_text='Whether to display SQL error messages to user')),
                ('difficulty', models.IntegerField(help_text='Difficulty rating from 1 (easiest) to 10 (hardest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('order', models.IntegerField(default=0, help_text='Display order in listing')),
                ('color', colorfield.fields.ColorField(default='#007bff', help_text='Color to represent this exercise', image_field=None, max_length=18, samples=None)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
