# Generated by Django 4.2.10 on 2025-04-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='allow_js',
            field=models.BooleanField(default=False, help_text='Enable JavaScript mode for interactive SQL execution'),
        ),
    ]
