# Generated by Django 4.2.10 on 2025-04-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_allow_js'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='placeholders',
            field=models.JSONField(blank=True, default=list, editable=False, help_text="List of placeholder definitions. Format: [{'name': 'name', 'type': 'str|int|regex', 'regex_pattern': 'optional pattern'}]"),
        ),
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Placeholder name (without the colon)', max_length=50)),
                ('type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('regex', 'Regular Expression')], default='str', help_text='Data type for validation', max_length=10)),
                ('regex_pattern', models.CharField(blank=True, help_text='Pattern to validate input (only for regex type)', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Description of the placeholder for the admin interface', max_length=255)),
                ('sanitize_js', models.TextField(blank=True, default='// This function sanitizes the input value\n// Parameter: value - the raw input from the user\n// Returns: the sanitized value\nfunction sanitize(value) {\n  // By default, return the value unchanged\n  return value;\n}', help_text="JavaScript function to sanitize input (parameter: 'value', returns sanitized value)")),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_set', to='exercises.exercise')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('exercise', 'name')},
            },
        ),
    ]
