# Generated by Django 4.2.10 on 2025-04-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercise_placeholders_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='anti_flag',
            field=models.CharField(blank=True, help_text='Text that must NOT appear in results for the query to be successful (case-insensitive check)', max_length=255, null=True),
        ),
    ]
