# Generated by Django 4.2.10 on 2025-04-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_anti_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='color',
        ),
    ]
