# Generated by Django 4.2.10 on 2025-04-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_color_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the category')),
                ('order', models.IntegerField(default=0, help_text='Display order in listing')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category this exercise belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='exercises.category'),
        ),
    ]
