# Generated by Django 4.2.10 on 2025-04-29 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_category_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exercise',
            name='solve_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this exercise has been solved'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exercise',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this exercise has been viewed'),
        ),
    ]
