# Generated by Django 4.2.10 on 2025-04-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_exercise_created_at_exercise_solve_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='hints',
            field=models.TextField(blank=True, help_text="Optional hints for the exercise (supports markdown). Multiple hints can be separated with '---'", null=True),
        ),
    ]
