# Generated by Django 4.2.10 on 2025-04-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_exercise_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholder',
            name='default_value',
            field=models.CharField(blank=True, help_text='Default value for the placeholder', max_length=255),
        ),
    ]
